// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
  Create as $Create,
} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ModelIntializer(
  method: $models.Method,
  reqURL: string,
  headers: $models.KV[],
): $CancellablePromise<$models.Scoop | null> {
  return $Call.ByID(766419187, method, reqURL, headers).then(($result: any) => {
    return $$createType1($result);
  });
}

export function SubmitRequest(s: $models.Scoop | null): $CancellablePromise<$models.Response> {
  return $Call.ByID(3693034122, s).then(($result: any) => {
    return $$createType2($result);
  });
}

// Private type creation functions
const $$createType0 = $models.Scoop.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.Response.createFrom;
