// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
  Create as $Create,
} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddQueryParams(s: $models.Scoop | null): $CancellablePromise<void> {
  return $Call.ByID(1676166479, s);
}

export function CreateCollection(c: $models.Collection): $CancellablePromise<boolean> {
  return $Call.ByID(918511024, c);
}

export function CreateRequest(
  c: $models.Collection,
  r: $models.Request,
): $CancellablePromise<boolean> {
  return $Call.ByID(2259185493, c, r);
}

export function ModelIntializer(
  method: $models.Method,
  reqURL: string,
  headers: $models.KV[],
  qParams: $models.KV[],
): $CancellablePromise<$models.Request> {
  return $Call.ByID(3595892640, method, reqURL, headers, qParams).then(($result: any) => {
    return $$createType0($result);
  });
}

export function OpenCollections(): $CancellablePromise<$models.Collection[]> {
  return $Call.ByID(3631902541).then(($result: any) => {
    return $$createType2($result);
  });
}

export function SaveCollection(c: $models.Collection): $CancellablePromise<boolean> {
  return $Call.ByID(711771153, c);
}

export function SaveScoop(s: $models.Scoop, c: $models.Collection): $CancellablePromise<boolean> {
  return $Call.ByID(1153602115, s, c);
}

export function SubmitRequest(s: $models.Scoop): $CancellablePromise<void> {
  return $Call.ByID(914496385, s);
}

// Private type creation functions
const $$createType0 = $models.Request.createFrom;
const $$createType1 = $models.Collection.createFrom;
const $$createType2 = $Create.Array($$createType1);
