// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Collection {
  "name": string;
  "scoops": Scoop[];

  /** Creates a new Collection instance. */
  constructor($$source: Partial<Collection> = {}) {
    if (!("name" in $$source)) {
      this["name"] = "";
    }
    if (!("scoops" in $$source)) {
      this["scoops"] = [];
    }

    Object.assign(this, $$source);
  }

  /**
   * Creates a new Collection instance from a string or object.
   */
  static createFrom($$source: any = {}): Collection {
    const $$createField1_0 = $$createType1;
    let $$parsedSource = typeof $$source === "string" ? JSON.parse($$source) : $$source;
    if ("scoops" in $$parsedSource) {
      $$parsedSource["scoops"] = $$createField1_0($$parsedSource["scoops"]);
    }
    return new Collection($$parsedSource as Partial<Collection>);
  }
}

export class KV {
  "key": string;
  "value": string;

  /** Creates a new KV instance. */
  constructor($$source: Partial<KV> = {}) {
    if (!("key" in $$source)) {
      this["key"] = "";
    }
    if (!("value" in $$source)) {
      this["value"] = "";
    }

    Object.assign(this, $$source);
  }

  /**
   * Creates a new KV instance from a string or object.
   */
  static createFrom($$source: any = {}): KV {
    let $$parsedSource = typeof $$source === "string" ? JSON.parse($$source) : $$source;
    return new KV($$parsedSource as Partial<KV>);
  }
}

export enum Method {
  /**
   * The Go zero value for the underlying type of the enum.
   */
  $zero = "",

  Get = "GET",
  Post = "POST",
  Put = "PUT",
  Patch = "PATCH",
  Delete = "DELETE",
  Empty = "",
}

export class Request {
  "name": string;
  "method": Method;
  "url": string;
  "headers": KV[];
  "query_params": KV[];

  /** Creates a new Request instance. */
  constructor($$source: Partial<Request> = {}) {
    if (!("name" in $$source)) {
      this["name"] = "";
    }
    if (!("method" in $$source)) {
      this["method"] = Method.$zero;
    }
    if (!("url" in $$source)) {
      this["url"] = "";
    }
    if (!("headers" in $$source)) {
      this["headers"] = [];
    }
    if (!("query_params" in $$source)) {
      this["query_params"] = [];
    }

    Object.assign(this, $$source);
  }

  /**
   * Creates a new Request instance from a string or object.
   */
  static createFrom($$source: any = {}): Request {
    const $$createField3_0 = $$createType3;
    const $$createField4_0 = $$createType3;
    let $$parsedSource = typeof $$source === "string" ? JSON.parse($$source) : $$source;
    if ("headers" in $$parsedSource) {
      $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
    }
    if ("query_params" in $$parsedSource) {
      $$parsedSource["query_params"] = $$createField4_0($$parsedSource["query_params"]);
    }
    return new Request($$parsedSource as Partial<Request>);
  }
}

export class Response {
  "status": string;
  "status_code": number;
  "headers": KV[];
  "body": string;
  "duration": number;
  "content_type": string;

  /** Creates a new Response instance. */
  constructor($$source: Partial<Response> = {}) {
    if (!("status" in $$source)) {
      this["status"] = "";
    }
    if (!("status_code" in $$source)) {
      this["status_code"] = 0;
    }
    if (!("headers" in $$source)) {
      this["headers"] = [];
    }
    if (!("body" in $$source)) {
      this["body"] = "";
    }
    if (!("duration" in $$source)) {
      this["duration"] = 0;
    }
    if (!("content_type" in $$source)) {
      this["content_type"] = "";
    }

    Object.assign(this, $$source);
  }

  /**
   * Creates a new Response instance from a string or object.
   */
  static createFrom($$source: any = {}): Response {
    const $$createField2_0 = $$createType3;
    let $$parsedSource = typeof $$source === "string" ? JSON.parse($$source) : $$source;
    if ("headers" in $$parsedSource) {
      $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
    }
    return new Response($$parsedSource as Partial<Response>);
  }
}

export class Scoop {
  "request": Request;
  "response": Response;

  /** Creates a new Scoop instance. */
  constructor($$source: Partial<Scoop> = {}) {
    if (!("request" in $$source)) {
      this["request"] = new Request();
    }
    if (!("response" in $$source)) {
      this["response"] = new Response();
    }

    Object.assign(this, $$source);
  }

  /**
   * Creates a new Scoop instance from a string or object.
   */
  static createFrom($$source: any = {}): Scoop {
    const $$createField0_0 = $$createType4;
    const $$createField1_0 = $$createType5;
    let $$parsedSource = typeof $$source === "string" ? JSON.parse($$source) : $$source;
    if ("request" in $$parsedSource) {
      $$parsedSource["request"] = $$createField0_0($$parsedSource["request"]);
    }
    if ("response" in $$parsedSource) {
      $$parsedSource["response"] = $$createField1_0($$parsedSource["response"]);
    }
    return new Scoop($$parsedSource as Partial<Scoop>);
  }
}

// Private type creation functions
const $$createType0 = Scoop.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = KV.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Request.createFrom;
const $$createType5 = Response.createFrom;
