// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
  Create as $Create,
} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckDNSOverride(s: $models.Scoop): $CancellablePromise<string> {
  return $Call.ByID(2022721066, s);
}

export function CreateCollection(c: $models.Collection): $CancellablePromise<boolean> {
  return $Call.ByID(510350185, c);
}

export function CreateDNSOverride(newOv: $models.DNSOverride): $CancellablePromise<boolean> {
  return $Call.ByID(1681865180, newOv);
}

export function CreateScoop(c: $models.Collection, s: $models.Scoop): $CancellablePromise<boolean> {
  return $Call.ByID(2777861803, c, s);
}

export function DeleteCollection(c: $models.Collection): $CancellablePromise<boolean> {
  return $Call.ByID(1606876506, c);
}

export function DeleteScoop(c: $models.Collection, s: $models.Scoop): $CancellablePromise<boolean> {
  return $Call.ByID(1062677162, c, s);
}

export function GenerateCurlCommand(s: $models.Scoop): $CancellablePromise<string> {
  return $Call.ByID(1905964093, s);
}

export function ModelIntializer(
  method: $models.Method,
  reqURL: string,
  headers: $models.KV[],
  qParams: $models.KV[],
  body: string,
): $CancellablePromise<$models.Request> {
  return $Call.ByID(619675979, method, reqURL, headers, qParams, body).then(($result: any) => {
    return $$createType0($result);
  });
}

export function OpenCollections(): $CancellablePromise<$models.Collection[]> {
  return $Call.ByID(201587754).then(($result: any) => {
    return $$createType2($result);
  });
}

export function OpenDNSOverrides(): $CancellablePromise<[$models.DNSOverride[], string]> {
  return $Call.ByID(1585073697).then(($result: any) => {
    $result[0] = $$createType4($result[0]);
    return $result;
  });
}

export function OverwriteDNSOverride(ov: $models.DNSOverride[]): $CancellablePromise<boolean> {
  return $Call.ByID(1980305549, ov);
}

export function RemoveCollectionDir(): $CancellablePromise<void> {
  return $Call.ByID(2810039768);
}

export function SaveCollection(c: $models.Collection): $CancellablePromise<boolean> {
  return $Call.ByID(806517476, c);
}

export function SaveScoop(s: $models.Scoop, c: $models.Collection): $CancellablePromise<boolean> {
  return $Call.ByID(325466900, s, c);
}

export function SubmitRequest(s: $models.Scoop): $CancellablePromise<void> {
  return $Call.ByID(605782002, s);
}

// Private type creation functions
const $$createType0 = $models.Request.createFrom;
const $$createType1 = $models.Collection.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.DNSOverride.createFrom;
const $$createType4 = $Create.Array($$createType3);
