// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
  Call as $Call,
  CancellablePromise as $CancellablePromise,
  Create as $Create,
} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckDNSOverride(s: $models.Scoop): $CancellablePromise<string> {
  return $Call.ByID(1746250071, s);
}

export function CheckServerHealth(s: $models.Server): $CancellablePromise<boolean> {
  return $Call.ByID(696586741, s);
}

export function CreateCollection(c: $models.Collection): $CancellablePromise<boolean> {
  return $Call.ByID(3995263080, c);
}

export function CreateDNSOverride(newOv: $models.DNSOverride): $CancellablePromise<boolean> {
  return $Call.ByID(3836349987, newOv);
}

export function CreateScoop(c: $models.Collection, s: $models.Scoop): $CancellablePromise<boolean> {
  return $Call.ByID(185534472, c, s);
}

export function DeleteCollection(c: $models.Collection): $CancellablePromise<boolean> {
  return $Call.ByID(1670052403, c);
}

export function DeleteScoop(c: $models.Collection, s: $models.Scoop): $CancellablePromise<boolean> {
  return $Call.ByID(1000232285, c, s);
}

export function GenerateCurlCommand(s: $models.Scoop): $CancellablePromise<string> {
  return $Call.ByID(2614130154, s);
}

export function GetFromServer(s: $models.Server): $CancellablePromise<boolean> {
  return $Call.ByID(1882007015, s);
}

export function ModelIntializer(
  method: $models.Method,
  reqURL: string,
  headers: $models.KV[],
  qParams: $models.KV[],
  body: string,
): $CancellablePromise<$models.Request> {
  return $Call.ByID(3321767416, method, reqURL, headers, qParams, body).then(($result: any) => {
    return $$createType0($result);
  });
}

export function OpenCollections(): $CancellablePromise<$models.Collection[]> {
  return $Call.ByID(151297045).then(($result: any) => {
    return $$createType2($result);
  });
}

export function OpenDNSOverrides(): $CancellablePromise<[$models.DNSOverride[], string]> {
  return $Call.ByID(2530218684).then(($result: any) => {
    $result[0] = $$createType4($result[0]);
    return $result;
  });
}

export function OpenSyncServer(): $CancellablePromise<$models.Server> {
  return $Call.ByID(808812320).then(($result: any) => {
    return $$createType5($result);
  });
}

export function OverwriteDNSOverride(ov: $models.DNSOverride[]): $CancellablePromise<boolean> {
  return $Call.ByID(3942158868, ov);
}

export function SaveCollection(c: $models.Collection): $CancellablePromise<boolean> {
  return $Call.ByID(1747504841, c);
}

export function SaveScoop(s: $models.Scoop, c: $models.Collection): $CancellablePromise<boolean> {
  return $Call.ByID(2695869835, s, c);
}

export function SendToServer(s: $models.Server): $CancellablePromise<boolean> {
  return $Call.ByID(1927157584, s);
}

export function SetSyncServer(s: $models.Server): $CancellablePromise<boolean> {
  return $Call.ByID(1313723400, s);
}

export function SubmitRequest(s: $models.Scoop): $CancellablePromise<void> {
  return $Call.ByID(1296865225, s);
}

// Private type creation functions
const $$createType0 = $models.Request.createFrom;
const $$createType1 = $models.Collection.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.DNSOverride.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.Server.createFrom;
